/**:
  ros__parameters:
    manager:
      odometry: odometry
      goal_topic: goal_pose
      base_frame: gimbal_yaw
      max_vel_: 2.5
      max_acc_: 0.8
      max_jerk_: 1.0
      dynamic_environment: 0
      control_points_distance: 0.5
      cmd_vel: cmd_vel
      control_cmd_frequency: 100
      safety_cheak_frequency: 20
      plan_cheak_frequency: 20
      control_output: true
      CarType: 0 # 0是圆形底盘 1是矩形底盘
      #矩形底盘长宽,当为圆形底盘时，取Car_L为半径，单位为m
      Car_L : 0.2
      Car_W : 0.3
      safe_check_distance : 5.0
      predict_collision_sample_step : 2
      predict_collision_danger_limit : 3
    sdf_map:
      use_global_map: true
      #没全局地图时使用
      map_size_x: 30.0
      map_size_y: 30.0
      resolusion_: 0.05
      # origin_x: -6.35
      # origin_y: -7.6
      #有全局地图时使用
      global_map_num: 1
      global_map_path:
      
       #- "/home/hy/wust_planner/src/planner_manager/map/rmuc_2025.yaml"
       #- "/home/hy/wust_planner/src/planner_manager/map/RMUC2025.yaml"

      
       - "/home/hy/wust_planner/src/planner_manager/map/rmuc_2025a.yaml"
      localmap:
        pointcloud_topic: terrain_map
        blind_distance: 0.2
        min_obstacle_intensity: 0.2
        max_obstacle_intensity: 2.0
        min_obstacle_height: 0.1
        max_obstacle_height: 0.4
      gobalmap_online:
        pointcloud_topic: terrain_map_ext
        blind_distance: 5.0
        min_obstacle_intensity: 0.1
        max_obstacle_intensity: 2.0
        min_obstacle_height: -0.5
        max_obstacle_height: 2.5
      
      show_esdf_time: false
      local_update_range_x: 5.0
      local_update_range_y: 5.0
      local_map_margin: 10
      frame_id: map
      obstacles_inflation: 0.0001
    search:
      max_tau: 1.0
      init_max_tau: 0.5
      lambda_heu: 5.0
      max_vel: 2.5
      max_acc: 0.8
      w_time: 5.0
      horizon: 100.0
      near_end_threshold: 0.2
      resolution_astar: 0.05
      time_resolution: 0.8
      allocate_num: 1000000
      check_num: 30

    optimization:
      max_vel: 2.5
      max_acc: 0.8
      dist0: 0.6
      jerk_smoothness_weight: 10.0
      distance_weight: 10.0
      feasibility_weight: 0.00001
      end_point_weight: 0.05
      guide_cost_weight: -1.0
      visibility_cost_weight: -1.0
      waypoints_cost_weight: 100.0
      acc_smoothness: -1.0
      max_iteration_num1: 2
      max_iteration_num2: 300
      max_iteration_num3: 200
      max_iteration_num4: 200
      max_iteration_time1: 0.0001
      max_iteration_time2: 0.005
      max_iteration_time3: 0.003
      max_iteration_time4: 0.003
      quadratic_cost: 11
      general_cost: 15
      order: 3
    
    mpc:
      weight_p: 500.0
      weight_yaw: 0.1
      weight_v: 10.0
      weight_w: 5.5


